version: '3.8'

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: bigbasket_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bigbasket_local
    volumes:
      - ./backend/Database/bigbasket_snapshot.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d bigbasket_local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: bigbasket_backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/bigbasket_local
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: bash -c "uvicorn app:app --host 0.0.0.0 --port 8000 --reload"

  frontend:
    build: ./frontend
    container_name: bigbasket_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  pgdata:


networks:
  app-network:
    driver: bridge
